name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/
 # Job pour construire et pousser l'image Docker
  build-and-push:
    runs-on: ubuntu-latest
    needs: tests
    if: success()
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

      - name: Log in to Private Docker Registry
        uses: docker/login-action@v2
        with:
          registry: my-private-registry.com
          username: ${{ secrets.PRIVATE_DOCKER_USERNAME }}
          password: ${{ secrets.PRIVATE_DOCKER_PASSWORD }}

      - name: Push Docker image to Private Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/flask-app:latest my-private-registry.com/flask-app:latest
          docker push my-private-registry.com/flask-app:latest

  # Job pour envoyer une notification en cas d'échec
  notify-failure:
    runs-on: ubuntu-latest
    needs: [tests, build-and-push]
    if: failure()
    
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions - Échec des tests"
          to: "admin@example.com"
          from: "GitHub Actions <admin@example.com>"
          body: "Les tests ont échoué sur la branche main. Merci de vérifier les logs."
